
== Gathering artifacts ==

== Publishing artifacts ==

Publishing artifact TradePulse.ipa
Publishing TradePulse.ipa to App Store Connect
> app-store-connect publish --path /Users/builder/clone/ipa/TradePulse.ipa --key-id @env:APP_STORE_CONNECT_KEY_IDENTIFIER --issuer-id @env:APP_STORE_CONNECT_ISSUER_ID --private-key @env:APP_STORE_CONNECT_PRIVATE_KEY
usage: app-store-connect publish [-h] [--log-api-calls] [--api-unauthorized-retries UNAUTHORIZED_REQUEST_RETRIES] [--api-server-error-retries SERVER_ERROR_RETRIES] [--disable-jwt-cache] [--json] [--issuer-id ISSUER_ID] [--key-id KEY_IDENTIFIER] [--private-key PRIVATE_KEY] [--certificates-dir CERTIFICATES_DIRECTORY] [--profiles-dir PROFILES_DIRECTORY] [--path artifact-path [artifact-path ...]] [--apple-id APPLE_ID] [--password APP_SPECIFIC_PASSWORD] [--enable-package-validation] [--skip-package-validation] [--skip-package-upload] [--max-find-build-wait MAX_FIND_BUILD_WAIT] [--max-build-processing-wait MAX_BUILD_PROCESSING_WAIT] [--beta-build-localizations BETA_BUILD_LOCALIZATIONS] [--testflight] [--expire-build-submitted-for-review] [--beta-group beta-group [beta-group ...]] [--app-store] [--platform {IOS,MAC_OS,TV_OS}] [--cancel-previous-submissions] [--app-store-version-info APP_STORE_VERSION_INFO] [--copyright COPYRIGHT] [--earliest-release-date EARLIEST_RELEASE_DATE] [--release-type {MANUAL,AFTER_APPROVAL,SCHEDULED}] [--version-string VERSION_STRING] [--description DESCRIPTION] [--keywords KEYWORDS] [--marketing-url MARKETING_URL] [--promotional-text PROMOTIONAL_TEXT] [--support-url SUPPORT_URL] [--app-store-version-localizations APP_STORE_VERSION_LOCALIZATIONS] [--phased-release] [--no-phased-release] [--locale {ar-SA,ca,cs,da,de-DE,el,en-AU,en-CA,en-GB,en-US,es-ES,es-MX,fi,fr-CA,fr-FR,he,hi,hr,hu,id,it,ja,ko,ms,nl-NL,no,pl,pt-BR,pt-PT,ro,ru,sk,sv,th,tr,uk,vi,zh-Hans,zh-Hant}] [--whats-new WHATS_NEW] [--altool-retries ALTOOL_RETRIES_COUNT] [--altool-retry-wait ALTOOL_RETRY_WAIT] [--altool-verbose-logging] [--altool-additional-arguments ALTOOL_ADDITIONAL_ARGUMENTS] [--log-stream {stderr,stdout}] [--no-color] [--version] [-s] [-v]
app-store-connect publish: error: argument --private-key: Provided value in environment variable "APP_STORE_CONNECT_PRIVATE_KEY" is not valid. Provided value is not a valid PEM encoded private key

Failed to publish TradePulse.ipa to App Store Connect.

Build failed :|


Publishing failed :|
Failed to publish TradePulse.ipa to App Store Connect.

estflight: true
